# Generated by Django 4.2.7 on 2023-11-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanalysis',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='projectname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
