# Generated by Django 4.2.7 on 2023-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fileanalysis_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanalysis',
            name='remark',
            field=models.CharField(max_length=255),
        ),
    ]
