# Generated by Django 4.2.7 on 2023-11-28 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fileanalysis_cad_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanalysis',
            name='projectname',
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='remark',
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='note',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='uploadfile',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dwg', 'dxf', 'step', 'iges'])]),
        ),
    ]
