# Generated by Django 4.2.7 on 2023-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_fileanalysis_projectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanalysis',
            name='uploadfile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
